name: Deploy site to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "github-pages"
  cancel-in-progress: true

jobs:
  parse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Create exercises directory
        run: |
          mkdir exercises

      - name: Parse exercises
        run: |
          cd parser
          python ne.py
          cd ..

      - uses: actions/upload-artifact@v7
        with:
          name: exercises
          path: exercises/

  prepare:
    runs-on: ubuntu-latest
    needs: parse
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v8
        with:
          name: exercises
          path: exercises/

      - name: Copy index.html
        run: |
          mkdir dist
          cp index.html dist/index.html

      - name: Copy js & css
        run: |
          viewer=$(uuidgen)
          mkdir dist/$viewer
          cp -r viewer/. dist/$viewer/
          sed -i "s/viewer/$viewer/g" dist/index.html

      - name: Copy exercises
        run: |
          exercises=$(uuidgen)
          mkdir dist/$exercises
          cp -r exercises/. dist/$exercises/
          sed -i "s/exercises/$exercises/g" dist/index.html

      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/deploy-pages@v4
