name: Deploy static site to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "github-pages"
  cancel-in-progress: true

jobs:
  parse:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.14"]
    steps:
      - name: Checkout my repository
        uses: actions/checkout@v4

      - name: Create exercises directory
        run: |
          mkdir exercises

      - name: Parse exercises
        run: |
          cd parser
          python ne.py
          cd ..

  prepare:
    runs-on: ubuntu-latest
    needs: parse
    steps:
      - name: Copy index.html
        run: |
          mkdir dist
          cp index.html dist/index.html

      - name: Copy js & css
        run: |
          viewer=$(uuidgen)
          mkdir dist/$viewer
          cp -r viewer/. dist/$viewer/
          sed -i "s/viewer/$viewer/g" dist/index.html

      - name: Copy exercises
        run: |
          exercises=$(uuidgen)
          mkdir dist/$exercises
          cp -r exercises/. dist/$exercises/
          sed -i "s/exercises/$exercises/g" dist/index.html

      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
